In [36]:
import pandas as pd
df = pd.read_csv("novagen_dataset.csv")

In [37]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [38]:
df.isnull().sum()

Age                      0
BMI                      0
Blood_Pressure           0
Cholesterol              0
Glucose_Level            0
Heart_Rate               0
Sleep_Hours              0
Exercise_Hours           0
Water_Intake             0
Stress_Level             0
Target                   0
Smoking                  0
Alcohol                  0
Diet                     0
MentalHealth             0
PhysicalActivity         0
MedicalHistory           0
Allergies                0
Diet_Type__Vegan         0
Diet_Type__Vegetarian    0
Blood_Group_AB           0
Blood_Group_B            0
Blood_Group_O            0
dtype: int64

In [39]:
df.head()
df.shape

(9549, 23)

In [40]:
df.columns

Index(['Age', 'BMI', 'Blood_Pressure', 'Cholesterol', 'Glucose_Level',
       'Heart_Rate', 'Sleep_Hours', 'Exercise_Hours', 'Water_Intake',
       'Stress_Level', 'Target', 'Smoking', 'Alcohol', 'Diet', 'MentalHealth',
       'PhysicalActivity', 'MedicalHistory', 'Allergies', 'Diet_Type__Vegan',
       'Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B',
       'Blood_Group_O'],
      dtype='object')

In [41]:
# one hot encoding

cols=["Diet_Type__Vegan","Diet_Type__Vegetarian","Blood_Group_AB","Blood_Group_B","Blood_Group_O","Smoking","Alcohol"]

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
encoded = ohe.fit_transform(df[cols])
encoded

array([[0., 1., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(9549, 9))

In [42]:
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(cols), index=df.index)

df= pd.concat( [ df.drop(columns=cols) , encoded_df ] , axis=1 )

In [43]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Allergies,Diet_Type__Vegan_True,Diet_Type__Vegetarian_True,Blood_Group_AB_True,Blood_Group_B_True,Blood_Group_O_True,Smoking_1,Smoking_2,Alcohol_1,Alcohol_2
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [45]:
X = df.drop(columns=["Target"])
y = df["Target"]

In [49]:
# y.head()

In [50]:
# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [51]:
# scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [64]:
# Logistic regression

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression( max_iter=2000 )
lr.fit(X_train, y_train)
y_pred_test = lr.predict(X_test)
y_pred_train = lr.predict(X_train)

from sklearn.metrics import accuracy_score, classification_report
print("LogisticRegression")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

LogisticRegression
accuracy_score_train: 0.8135846798324357
accuracy_score_test: 0.8230366492146597
classification_report:
               precision    recall  f1-score   support

           0       0.82      0.81      0.81      1356
           1       0.83      0.84      0.83      1509

    accuracy                           0.82      2865
   macro avg       0.82      0.82      0.82      2865
weighted avg       0.82      0.82      0.82      2865

In [62]:
# KNN

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# Hyper parameter tuning
knn = KNeighborsClassifier()
param_grid={"n_neighbors":[3,5,7,9]}

grid = GridSearchCV(
    knn,
    param_grid
)

grid.fit(X_train, y_train)

print(grid.best_params_)    #9

{'n_neighbors': 9}

In [63]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)
y_pred_train = knn.predict(X_train)
y_pred_test = knn.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("KNN Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

KNN Classifier
accuracy_score_train: 0.9046977857570317
accuracy_score_test: 0.8621291448516579
classification_report:
               precision    recall  f1-score   support

           0       0.85      0.86      0.86      1356
           1       0.87      0.86      0.87      1509

    accuracy                           0.86      2865
   macro avg       0.86      0.86      0.86      2865
weighted avg       0.86      0.86      0.86      2865

In [57]:
# Decision tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtc = DecisionTreeClassifier()
param_grid={
    "max_depth":[2,3,4,5,6,7,8,9,10],
    "min_samples_leaf":[20,30,50],
    "min_samples_split":[5,10,15,20,25]
}

dtc_grid= GridSearchCV(
    dtc,
    param_grid,
    cv=5
)

dtc_grid.fit(X_train,y_train)
print(dtc_grid.best_params_)

{'max_depth': 10, 'min_samples_leaf': 20, 'min_samples_split': 5}

In [58]:
dtc = DecisionTreeClassifier(
    max_depth=10,
    min_samples_leaf=20,
    min_samples_split=5
)

dtc.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=20, min_samples_split=5)

In [61]:
y_pred_train = dtc.predict(X_train)
y_pred_test = dtc.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Decision Tree Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

Decision Tree Classifier
accuracy_score_train: 0.8966187911430281
accuracy_score_test: 0.8855148342059337
classification_report:
               precision    recall  f1-score   support

           0       0.87      0.90      0.88      1356
           1       0.91      0.87      0.89      1509

    accuracy                           0.89      2865
   macro avg       0.89      0.89      0.89      2865
weighted avg       0.89      0.89      0.89      2865

In [69]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred_train = gnb.predict(X_train)
y_pred_test = gnb.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Naive Bayes")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

Naive Bayes
accuracy_score_train: 0.8073010173548774
accuracy_score_test: 0.8233856893542757
classification_report:
               precision    recall  f1-score   support

           0       0.80      0.83      0.82      1356
           1       0.84      0.82      0.83      1509

    accuracy                           0.82      2865
   macro avg       0.82      0.82      0.82      2865
weighted avg       0.82      0.82      0.82      2865

In [74]:
# support vector classifier ( SVC )

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc = SVC()
param_grid={
    "kernel":['rbf', 'linear', 'poly', 'sigmoid'],
    "C":[0.5,1,2,3,4,5]
}

svc_grid = GridSearchCV(
    svc,
    param_grid,
    scoring="f1"
)

svc_grid.fit(X_train, y_train)
print(svc_grid.best_params_)
print(svc_grid.best_score_)

{'C': 5, 'kernel': 'rbf'}
0.9340193803600098

In [75]:
svc = SVC(C=5, kernel='rbf')
svc.fit(X_train, y_train)

y_pred_train = svc.predict(X_train)
y_pred_test = svc.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Support Vector Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

Support Vector Classifier
accuracy_score_train: 0.9829443447037702
accuracy_score_test: 0.9329842931937172
classification_report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93      1356
           1       0.93      0.94      0.94      1509

    accuracy                           0.93      2865
   macro avg       0.93      0.93      0.93      2865
weighted avg       0.93      0.93      0.93      2865

In [66]:
# Gradient boosting classifier

from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(
    learning_rate=0.1,
    n_estimators=200,
    max_depth=3,
    random_state=42
)

gbc.fit(X_train, y_train)

GradientBoostingClassifier(n_estimators=200, random_state=42)

In [67]:
y_pred_train = gbc.predict(X_train)
y_pred_test = gbc.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Gradient Boosting Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

Gradient Boosting Classifier
accuracy_score_train: 0.9470377019748654
accuracy_score_test: 0.9315881326352531
classification_report:
               precision    recall  f1-score   support

           0       0.93      0.92      0.93      1356
           1       0.93      0.94      0.94      1509

    accuracy                           0.93      2865
   macro avg       0.93      0.93      0.93      2865
weighted avg       0.93      0.93      0.93      2865

In [76]:
# random forest classifier

from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(
    n_estimators=201,      # odd
    oob_score=True,    # provides an unbiased, real-time estimate of how well a model will perform on unseen data
    max_depth=4
)

rfc.fit(X_train, y_train)

y_pred_train = rfc.predict(X_train)
y_pred_test = rfc.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Gradient Boosting Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))
print("OOB score:",rfc.oob_score_)

Gradient Boosting Classifier
accuracy_score_train: 0.8421603830041892
accuracy_score_test: 0.8506108202443281
classification_report:
               precision    recall  f1-score   support

           0       0.89      0.78      0.83      1356
           1       0.82      0.91      0.87      1509

    accuracy                           0.85      2865
   macro avg       0.86      0.85      0.85      2865
weighted avg       0.85      0.85      0.85      2865

OOB score: 0.8357271095152603

In [77]:
# voting classifier

from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

lr = LogisticRegression( max_iter=2000 )
knn = KNeighborsClassifier( n_neighbors=9 )
rfc = RandomForestClassifier( n_estimators=201 )

vc = VotingClassifier(
    estimators=[
        ("lr",lr),
        ("knn",knn),
        ("rfc",rfc)
    ],
    voting="hard"
)

vc.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(max_iter=2000)),
                             ('knn', KNeighborsClassifier(n_neighbors=9)),
                             ('rfc', RandomForestClassifier(n_estimators=201))])

In [78]:
y_pred_train = vc.predict(X_train)
y_pred_test = vc.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Voting Classifier")
print("accuracy_score_train:",accuracy_score(y_train, y_pred_train))
print("accuracy_score_test:",accuracy_score(y_test, y_pred_test))
print("classification_report:\n",classification_report(y_test, y_pred_test))

Voting Classifier
accuracy_score_train: 0.9452423698384201
accuracy_score_test: 0.912041884816754
classification_report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.91      1356
           1       0.91      0.92      0.92      1509

    accuracy                           0.91      2865
   macro avg       0.91      0.91      0.91      2865
weighted avg       0.91      0.91      0.91      2865