In [4]:
# in knn we are calculating distacnce so it is very important to scale the data

import pandas as pd
from sklearn.metrics import precision_score, accuracy_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [5]:
df= pd.read_csv("heart.csv")
X= df.drop(columns=["target"])
y=df["target"]

In [6]:
# X.head()
# y.head()

In [7]:
# train test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [8]:
# scaling

scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)
# X_train
# X_test

In [9]:
# model

knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred= knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))

Accuracy: 0.8524590163934426
Precision: 0.9259259259259259
recall_score: 0.78125

In [10]:
# k=5

knn= KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred= knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))

Accuracy: 0.9016393442622951
Precision: 0.9333333333333333
recall_score: 0.875

In [11]:
# k=7         # for k=7 we are getting the best value

knn= KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

y_pred= knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))

Accuracy: 0.9180327868852459
Precision: 0.9354838709677419
recall_score: 0.90625

In [16]:
# k=9

knn= KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)

y_pred= knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))

Accuracy: 0.9016393442622951
Precision: 0.9333333333333333
recall_score: 0.875

In [12]:
#  Cross validation for hyperparam tuning using GridSearchCV
# to improve the performance of knn

from sklearn.model_selection import GridSearchCV

knn= KNeighborsClassifier()
param_grid= {"n_neighbors": [3,5,7,9] }

classifierCV= GridSearchCV(
    knn,
    param_grid,
    cv=5,  # no. of folds
    scoring="recall"    # based on recall value we want to get the model    # if we dont specify by default it is calculating accuracy
)

classifierCV.fit(X_train, y_train)

y_pred= classifierCV.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))

# result
res= pd.DataFrame(classifierCV.cv_results_)
print(res[["param_n_neighbors","mean_test_score"]])

print(classifierCV.best_params_)             # for n_neighbors=7 we are getting the best value of recall

Accuracy: 0.9180327868852459
Precision: 0.9354838709677419
recall_score: 0.90625
   param_n_neighbors  mean_test_score
0                  3         0.864387
1                  5         0.857550
2                  7         0.871795
3                  9         0.856980
{'n_neighbors': 7}

In [13]:
# pipeline

from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

pipe = Pipeline([
    ('scaler', StandardScaler()), 
     ('knn', KNeighborsClassifier())
])

param_grid= {"knn__n_neighbors": [3,5,7,9] }

classifierCV= GridSearchCV(
    pipe,
    param_grid,
    cv=5,  # no. of folds
    scoring="recall"    # based on recall value we want to get the model    # if we dont specify by default it is calculating accuracy
)
classifierCV.fit(X_train, y_train)

y_pred= classifierCV.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("recall_score:",recall_score(y_test, y_pred))
print(classifierCV.best_params_)

Accuracy: 0.9180327868852459
Precision: 0.9354838709677419
recall_score: 0.90625
{'knn__n_neighbors': 7}

In [23]:
# Assignment

import pandas as pd
df= pd.read_csv("IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [40]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["species"]= le.fit_transform(df["species"])

In [41]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [45]:
X= df.drop(columns=["species"])
y= df["species"]
# X.head()
# y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [46]:
# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=42)

In [53]:
# knn

# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import accuracy_score, precision_score, recall_score

# knn= KNeighborsClassifier()
# param_grid= {"n_neighbors":[3,5,7,9]}
# classifierCV= GridSearchCV(
#     knn,
#     param_grid,
#     cv=5,
# )
# classifierCV.fit(X_train, y_train)
# y_pred= classifierCV.predict(X)
# print("Accuracy:",accuracy_score(y, y_pred))
# print("Precision:",precision_score(y, y_pred, average='macro'))
# print("Recall score:", recall_score(y, y_pred, average='macro'))
# print(classifierCV.best_params_)    # for 7 we get best accuracy (n_neighbors)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score

knn= KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred= knn.predict(X)
print("Accuracy:",accuracy_score(y, y_pred))
print("Precision:",precision_score(y, y_pred, average='macro'))
print("Recall score:", recall_score(y, y_pred, average='macro'))

Accuracy: 0.9466666666666667
Precision: 0.9507575757575758
Recall score: 0.9466666666666667

In [54]:
# Logistic regression

from sklearn.linear_model import LogisticRegression

model_lr= LogisticRegression( max_iter=1000 )
model_lr.fit(X_train, y_train)
y_pred= model_lr.predict(X)
print("Accuracy:",accuracy_score(y, y_pred))
print("Precision:",precision_score(y, y_pred, average='macro'))
print("Recall score:", recall_score(y, y_pred, average='macro'))

Accuracy: 0.9666666666666667
Precision: 0.9667867146858743
Recall score: 0.9666666666666667

In [55]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

gnb= GaussianNB()
gnb.fit(X_train, y_train)
y_pred= gnb.predict(X)

print("Accuracy:",accuracy_score(y, y_pred))
print("Precision:",precision_score(y, y_pred, average='macro'))
print("Recall score:", recall_score(y, y_pred, average='macro'))

Accuracy: 0.9533333333333334
Precision: 0.9534480458850206
Recall score: 0.9533333333333333